language: cpp 

os:
- linux
dist: trusty
sudo: required
services:
  - docker

compiler: 
- gcc 

before_install:
  - sudo docker build -t interceptor .
env: 
  matrix:
    - ENABLE_GZIP=on
    - ENABLE_GZIP=off
    - DEBUG_LOGGING=on
    - DEBUG_LOGGING=off
    - ENABLE_GZIP=on DEBUG_LOGGING=off
    - ENABLE_LOCAL_CACHE=on ENABLE_GZIP=on
    - ENABLE_LOCAL_CACHE=off ENABLE_GZIP=on
    - ENABLE_LOCAL_CACHE=on ENABLE_GZIP=off
    - ENABLE_LOCAL_CACHE=off ENABLE_GZIP=off

script: sudo docker run -v $PWD:/code -t interceptor /bin/bash -c "cd /code; cmake -DENABLE_GZIP=$ENABLE_GZIP -DDEBUG_LOGGING=$DDEBUG_LOGGING . && make && make install && make test"
