language: cpp 

os:
- linux
dist: trusty
sudo: required
services:
  - docker

compiler: 
- gcc 

before_install:
  - pip install --user codecov
  - sudo docker build -t interceptor .

after_success:
  - codecov

env: 
  matrix:
    - ENABLE_GZIP=on
    - ENABLE_GZIP=off
    - DEBUG_LOGGING=on
    - DEBUG_LOGGING=off
    - ENABLE_GZIP=on DEBUG_LOGGING=off
    - ENABLE_LOCAL_CACHE=on ENABLE_GZIP=on
    - ENABLE_LOCAL_CACHE=off ENABLE_GZIP=on
    - ENABLE_LOCAL_CACHE=on ENABLE_GZIP=off
    - ENABLE_LOCAL_CACHE=off ENABLE_GZIP=off

script: sudo docker run -v $PWD:/code -t interceptor /bin/bash -c "export ENABLE_GZIP=$ENABLE_GZIP; export DEBUG_LOGGING=$DEBUG_LOGGING; export ENABLE_LOCAL_CACHE=$ENABLE_LOCAL_CACHE; cd /code; cmake -DENABLE_GZIP=$ENABLE_GZIP -DDEBUG_LOGGING=$DEBUG_LOGGING . && make && make install && env CTEST_OUTPUT_ON_FAILURE=1 make test"
