language: cpp 

os:
- linux
dist: trusty
sudo: required
services:
  - docker

compiler: 
- gcc 

before_install:
  - docker-compose build -t interceptor
  - docker run -v ./:/code -t interceptor -c "cd /code; cmake -DENABLE_GZIP=$ENABLE_GZIP -DDEBUG_LOGGING=$DDEBUG_LOGGING . && make && sudo make install && make test"
env: 
  matrix:
    - ENABLE_GZIP=on
    - ENABLE_GZIP=off
    - DEBUG_LOGGING=on
    - DEBUG_LOGGING=off
    - ENABLE_GZIP=on DEBUG_LOGGING=off
    - ENABLE_LOCAL_CACHE=on ENABLE_GZIP=on
    - ENABLE_LOCAL_CACHE=off ENABLE_GZIP=on
    - ENABLE_LOCAL_CACHE=on ENABLE_GZIP=off
    - ENABLE_LOCAL_CACHE=off ENABLE_GZIP=off

script: cmake -DENABLE_GZIP=$ENABLE_GZIP -DDEBUG_LOGGING=$DEBUG_LOGGING . && make && sudo make install &&  make test
