language: cpp 

os:
- linux
dist: trusty
sudo: required

compiler: 
- gcc 
- clang 

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test 
- sudo apt-get -qq update
- sudo apt-get install -y libboost-all-dev zlib1g-dev
- sudo apt-get install -y gcc-5 g++-5
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1

install: cmake . && make
