language: cpp
os:
- linux
dist: trusty
sudo: required
services:
- docker
compiler:
- gcc
before_install:
- pip install --user codecov
- sudo docker build -t interceptor .
env:
  matrix:
  - ENABLE_GZIP=on ENABLE_SSL=on
  - ENABLE_GZIP=off ENABLE_SSL=off
  - DEBUG_LOGGING=on
  - DEBUG_LOGGING=off
  - ENABLE_GZIP=on DEBUG_LOGGING=off
  - ENABLE_LOCAL_CACHE=on ENABLE_GZIP=on ENABLE_SSL=on
  - ENABLE_LOCAL_CACHE=off ENABLE_GZIP=on ENABLE_SSL=on
  - ENABLE_LOCAL_CACHE=on ENABLE_GZIP=off ENABLE_SSL=off
  - ENABLE_LOCAL_CACHE=off ENABLE_GZIP=off ENABLE_SSL=on
  - ENABLE_LOCAL_CACHE=off ENABLE_GZIP=off ENABLE_SSL=off
script: sudo docker run -v $PWD:/code -t interceptor /bin/bash -c "export ENABLE_GZIP=$ENABLE_GZIP;
  export DEBUG_LOGGING=$DEBUG_LOGGING; export ENABLE_LOCAL_CACHE=$ENABLE_LOCAL_CACHE;
  cd /code; cmake -DENABLE_GZIP=$ENABLE_GZIP -DDEBUG_LOGGING=$DEBUG_LOGGING . && make
  && make install && env CTEST_OUTPUT_ON_FAILURE=1 make test"
before_deploy:
- git config --local user.name "bend66"
- git config --local user.email "ben.daccache@gmail.com"
- git tag
deploy:
  provider: releases
  api_key:
    secure: q7I3bwYpkCHXHQfJ61LMscxdfynJiJNq2IdOvo31DmbJkfPP1VngqgvToXYjMgfA7+FiSMExvgYDOnv157i+a9dif4omhTSAdxv044llD0HCULr9iIq2pM20kALgQqux9ioRynSO3+6iSoJkgLnAg2JQqzaZa0pSXNEFTZzOnVdh2p1RQx2Q3A5QjAwpXYx+3nRMjv01RLQUfJcL+oFOqmrUlP2ggAfomtrwQtCdoB95Qcqjo9d1RlYwfBwBxc4FS04yXKqPq4wkS/5Cc0SBcYuUH0H5YPCNZPm1cbMOzekFGrUAsENaMkaqGvqKRVI8mjdfUoFCH6MpdRTlHZrcw7XFqugVaiZpsnD0zAHu8kvDu9gNH+gRSX2CEck4zEid093ytPVMIXzkVvty7LIhrjbYnCdfS1SZV/de5O7GWahUjvwZKZJClnIAETnc9FOUK8zOFDH3si8gcWzwLLfLwN7ZWhZiw4vT2Wj+ETzcFUxiHoqqhi9iMWI3bFC/h6HPQdlT0Ip7SbaPcDqjtA+cZ22rcywt70/wy5SSOXlOiB2sojvlN8vck3pYtVv3LBaprGCRtGc07mVzgC82s/vyd1hz3plvYV5lcwM4NabRKIAtEIIqH/fVQqtFLgOvYnjeEJTe9ivPQLo2J4DC8RowjZFda5pplV+12NeeCVR1UX8=
  skip_cleanup: true
  file_glob: true
  file: 
    -interceptor*.tar.gz
  overwrite: true
  tag_name: $TRAVIS_TAG
  name: interceptor_ $TRAVIS_TAG
  body: automated build of interceptor $TRAVIS_TAG
  on:
    repo: bend/interceptor
    tags: true
    branch: master

